import { describe,it,expect } from "vitest";
import { createInitialState } from "../src/game/state";
import { activePlanet,selectPlanet } from "../src/game/empire";
import { createPlanet,HOMEWORLD_ID } from "../src/game/planet";
import { coordinateKey,homeCoordinates,npcAt,planetProperties,positionBonus,distance,validCoordinates,wrap } from "../src/game/galaxy";
import { abandonColony,advanceFleets,colonyCount,colonyLimit,emptyCargo,fleetSlots,flightSeconds,nextFleetEvent,quoteFlight,recallFleet,resolveFleetArrivals,sendFleet,shipEngine,type FleetRequest } from "../src/game/fleet";
import { big } from "../src/game/decimal";
import { tick,prestige } from "../src/game/logic";
import { catchUp } from "../src/core/offline";
import { deserializeState,exportSave,importSave,serializeState,loadGame } from "../src/game/save";
import { spaceView } from "../src/ui/space-present";
import { STORAGE_KEY } from "../src/game/content";
import { economy } from "../src/game/economy";
import type { GameState } from "../src/game/types";
function ready():GameState {
 const s=createInitialState(42),p=activePlanet(s);p.resources={metal:big(1e6),crystal:big(1e6),deuterium:big(1e6)};
 Object.assign(p.units,{small_cargo:20,colony_ship:3,espionage_probe:10,large_cargo:3});
 Object.assign(s.research.levels,{combustion_drive:6,impulse_drive:3,computer_tech:6,astrophysics:3});
 s.arcade.seed=123;s.protocols.slots.forEach(x=>x.card=null);return tick(s,0.1);
}
function target(s:GameState){const c=activePlanet(s).coordinates;for(let position=1;position<=15;position++){const t={...c,position};if(!npcAt(s,t)&&!s.planets.some(p=>coordinateKey(p.coordinates)===coordinateKey(t)))return t;}throw Error("no empty site");}
function request(s:GameState):FleetRequest{return {mission:"colonize",target:target(s),ships:{colony_ship:1,small_cargo:2},cargo:{metal:big(1000),crystal:big(500),deuterium:big(200)},speedPercent:100};}
function colony(){let s=ready();s=sendFleet(s,request(s)).state;return tick(s,nextFleetEvent(s));}
function freeze<T>(o:T):T{if(o&&typeof o==="object"&&!Object.isFrozen(o)){Object.values(o).forEach(freeze);Object.freeze(o);}return o;}
const copy=(s:GameState)=>serializeState(s);

describe("galaxy",()=>{
 it("has bounded coordinates, deep space opt-in and wrap",()=>{expect(validCoordinates({galaxy:1,system:1,position:16})).toBe(false);expect(validCoordinates({galaxy:1,system:1,position:16},true)).toBe(true);expect(wrap(0,100)).toBe(100);expect(wrap(101,100)).toBe(1);expect(validCoordinates({galaxy:1,system:NaN,position:1})).toBe(false);});
 it("matches the distance example and ring edges",()=>{const c={galaxy:1,system:1,position:8};expect(distance(c,{...c,system:2})).toBe(2795);expect(distance(c,{...c,system:100})).toBe(2795);expect(distance(c,{...c,galaxy:5})).toBe(20000);expect(distance(c,{...c,position:9})).toBe(1005);});
 it("matches 10% velocity 5000 flight example",()=>{expect(flightSeconds(2795,5000,10)).toBeCloseTo(69.0426,3);expect(()=>flightSeconds(NaN,5000,10)).toThrow();expect(()=>flightSeconds(2795,5000,0)).toThrow();});
 it("is deterministic without consuming ring RNG",()=>{const s=ready(),before=exportSave(s,1);const c=target(s);expect(planetProperties(42,c)).toEqual(planetProperties(42,c));for(let i=0;i<200;i++)npcAt(s,{galaxy:2,system:i%100+1,position:i%15+1});expect(exportSave(s,1)).toBe(before);});
 it("spawns home in specified range without changing home stats",()=>{for(let i=0;i<80;i++){const s=createInitialState(i),p=activePlanet(s);expect(p.coordinates).toEqual(homeCoordinates(i));expect(p.coordinates.system).toBeGreaterThanOrEqual(40);expect(p.coordinates.system).toBeLessThanOrEqual(60);expect(p.coordinates.position).toBeGreaterThanOrEqual(4);expect(p.coordinates.position).toBeLessThanOrEqual(12);expect(p.tempMax).toBe(40);expect(p.fieldsMax).toBe(163);expect(npcAt(s,p.coordinates)).toBe(null);}});
 it("occupation is roughly 25%, and deep space is never an NPC colony",()=>{const s=ready();let n=0;for(let system=1;system<=100;system++)for(let position=1;position<=15;position++)if(npcAt(s,{galaxy:2,system,position}))n++;expect(n/1500).toBeGreaterThan(.20);expect(n/1500).toBeLessThan(.30);expect(npcAt(s,{galaxy:2,system:1,position:16})).toBe(null);});
 it("position boosts affect mines but not base production or energy",()=>{const s=ready(),p=createPlanet("colony",{galaxy:1,system:1,position:8});s.planets.push(p);let a=selectPlanet(s,p.id);const baseline=economy(a);expect(baseline.gross.metal).toBe(economy(s).gross.metal);p.buildings.metal_mine=5;p.buildings.solar_plant=10;const boosted=economy(a);p.coordinates.position=5;const plain=economy(a);expect((boosted.gross.metal-baseline.gross.metal)/(plain.gross.metal-baseline.gross.metal)).toBeCloseTo(1.35,9);expect(boosted.demand).toBe(plain.demand);expect(positionBonus(1,"crystal")).toBe(1.4);});
});

describe("flight commands are atomic",()=>{
 it("quotes without mutations and deducts exactly once",()=>{const s=freeze(ready()),r=request(s),before=exportSave(s,1),q=quoteFlight(s,r);expect(q.ok).toBe(true);expect(exportSave(s,1)).toBe(before);const n=sendFleet(s,r).state;expect(activePlanet(n).units.colony_ship).toBe(2);expect(activePlanet(n).resources.metal.eq(activePlanet(s).resources.metal.sub(1000))).toBe(true);expect(activePlanet(n).resources.deuterium.eq(activePlanet(s).resources.deuterium.sub(200).sub(q.fuel))).toBe(true);expect(s.fleets).toHaveLength(0);});
 it.each(["negative-ships","fractional-ships","too-many","negative-cargo","capacity","bad-speed","deep","same-site","satellite","unknown","no-colonizer"])("refuses %s without spending",kind=>{const s=ready(),r=request(s);if(kind==="negative-ships")r.ships.small_cargo=-1;if(kind==="fractional-ships")r.ships.small_cargo=.5;if(kind==="too-many")r.ships.small_cargo=100;if(kind==="negative-cargo")r.cargo.metal=big(-1);if(kind==="capacity")r.cargo.metal=big(1e6);if(kind==="bad-speed")r.speedPercent=11;if(kind==="deep")r.target.position=16;if(kind==="same-site")r.target=activePlanet(s).coordinates;if(kind==="satellite")r.ships.solar_satellite=1;if(kind==="unknown")r.mission="attack" as never;if(kind==="no-colonizer")r.ships.colony_ship=0;const n=sendFleet(s,r);expect(n.ok).toBe(false);expect(n.state).toBe(s);});
 it("reserves both colony quota and coordinate",()=>{let s=ready();s.research.levels.astrophysics=1;const r=request(s);s=sendFleet(s,r).state;expect(sendFleet(s,r).ok).toBe(false);const other=request(s);other.target=target({...s,planets:[...s.planets,{...createPlanet("dummy"),coordinates:r.target}]});expect(sendFleet(s,other).ok).toBe(false);expect(colonyLimit(s)).toBe(1);expect(fleetSlots(s)).toBe(7);});
 it("engine upgrades and hyperspace cargo are included",()=>{const s=ready();const v=shipEngine(s,"small_cargo").speed;s.research.levels.impulse_drive=5;expect(shipEngine(s,"small_cargo").speed).toBeGreaterThan(v);const r=request(s);const cap=quoteFlight(s,r).capacity;s.research.levels.hyperspace_tech=10;expect(quoteFlight(s,r).capacity.eq(cap.mul(1.5))).toBe(true);});
 it("flight duration is frozen at launch even when drive technology changes",()=>{const s=ready();let n=sendFleet(s,request(s)).state;const duration=n.fleets[0]!.duration;n={...n,research:{...n.research,levels:{...n.research.levels,impulse_drive:100}}};n=tick(n,1);expect(n.fleets[0]!.duration).toBe(duration);expect(n.fleets[0]!.remaining).toBeCloseTo(duration-1,8);});
});

describe("arrivals, transfers, recall and reset",()=>{
 it("creates a colony only after actual arrival and consumes one colony ship",()=>{let s=ready();const r=request(s);s=sendFleet(s,r).state;expect(colonyCount(s)).toBe(0);const d=s.fleets[0]!.duration;s=tick(s,d);expect(colonyCount(s)).toBe(1);expect(s.planets[1]!.resources.metal.toNumber()).toBe(1000);expect(s.fleets[0]!.ships.colony_ship).toBe(0);expect(s.fleets[0]!.returning).toBe(true);expect(s.activePlanetId).toBe(HOMEWORLD_ID);s=tick(s,d);expect(s.fleets).toHaveLength(0);expect(activePlanet(s).units.small_cargo).toBe(20);expect(activePlanet(s).units.colony_ship).toBe(2);expect(resolveFleetArrivals(s)).toBe(s);});
 it("transport unloads once and returns only the ships",()=>{let s=colony();s=tick(s,nextFleetEvent(s));const r={...request(s),mission:"transport" as const,target:s.planets[1]!.coordinates,ships:{small_cargo:2}};let n=sendFleet(s,r).state;const d=n.fleets[0]!.duration;n=tick(n,d);expect(n.fleets[0]!.cargo.metal.eq(0)).toBe(true);const atArrival=n.planets[1]!.resources.metal;const further=tick(n,d);expect(further.planets[1]!.resources.metal.gte(atArrival)).toBe(true);expect(further.fleets).toHaveLength(0);expect(activePlanet(further).units.small_cargo).toBe(activePlanet(s).units.small_cargo);});
 it("transport is a transfer, not an increase to lifetime output",()=>{let s=colony();s=tick(s,nextFleetEvent(s));for(const p of s.planets)p.resources={metal:big(1e6),crystal:big(1e6),deuterium:big(1e6)};const r={...request(s),mission:"transport" as const,target:s.planets[1]!.coordinates,ships:{small_cargo:2}};const sent=sendFleet(s,r).state,n=tick(sent,sent.fleets[0]!.duration);expect(n.lifetime).toEqual(s.lifetime);expect(n.planets[1]!.resources.metal.toNumber()).toBeCloseTo(1001000,7);});
 it("deployment retains ships and removes task without creating a return",()=>{let s=colony();s=tick(s,nextFleetEvent(s));const r={...request(s),mission:"deploy" as const,target:s.planets[1]!.coordinates,ships:{small_cargo:2}};s=sendFleet(s,r).state;s=tick(s,s.fleets[0]!.duration);expect(s.fleets).toHaveLength(0);expect(s.planets[1]!.units.small_cargo).toBe(2);});
 it("recall releases reservation and uses actual elapsed flight time",()=>{const s=ready();let n=sendFleet(s,request(s)).state;n=tick(n,1);n=recallFleet(n,n.fleets[0]!.id).state;expect(n.fleets[0]!.remaining).toBeCloseTo(1,8);expect(recallFleet(n,n.fleets[0]!.id).ok).toBe(false);n=tick(n,1);expect(n.planets).toHaveLength(1);expect(activePlanet(n).units.colony_ship).toBe(3);});
 it("immediate recall is settled once",()=>{const s=ready(),n=sendFleet(s,request(s)).state;const recalled=recallFleet(n,1).state;expect(recalled.fleets).toHaveLength(0);expect(recallFleet(recalled,1).state).toBe(recalled);});
 it("scouting produces a message, without creating combat or altering RNG",()=>{let s=ready();const seed=s.arcade.seed;const r={...request(s),mission:"scout" as const,ships:{espionage_probe:2},cargo:emptyCargo()};s=sendFleet(s,r).state;s=tick(s,2*s.fleets[0]!.duration);expect(s.messages.some(m=>m.id.startsWith("scout-")&&m.text.includes("侦察报告"))).toBe(true);expect(s.fleets).toHaveLength(0);expect(s.arcade.seed).toBe(seed);});
 it("failed destination returns ships and cargo rather than deleting them",()=>{let s=ready(),r=request(s);s=sendFleet(s,r).state;s={...s,research:{...s.research,levels:{...s.research.levels,astrophysics:0}}};s=tick(s,2*s.fleets[0]!.duration);expect(s.planets).toHaveLength(1);expect(activePlanet(s).units.colony_ship).toBe(3);expect(activePlanet(s).resources.metal.eq(1e6)).toBe(true);});
 it("long offline tick equals short ticks across colony creation and return",()=>{const s=sendFleet(ready(),request(ready())).state;const long=tick(freeze(s),90,"offline");let small=s;for(let i=0;i<360;i++)small=tick(small,.25,"offline");expect(long.fleets).toEqual(small.fleets);expect(long.messages.map(m=>m.id)).toEqual(small.messages.map(m=>m.id));expect(long.totalTime.sub(small.totalTime).abs().lt(1e-7)).toBe(true);for(let i=0;i<long.planets.length;i++)for(const id of ["metal","crystal","deuterium"] as const)expect(long.planets[i]!.resources[id].toNumber()).toBeCloseTo(small.planets[i]!.resources[id].toNumber(),5);});
 it("the offline cap includes flights",()=>{const s=sendFleet(ready(),request(ready())).state;const cap=catchUp(s,100000);expect(cap.appliedSeconds).toBe(7200);expect(copy(cap.state)).toEqual(copy(tick(s,7200,"offline")));});
 it("guards abandonment while tasks reference the planet, never allows home abandonment",()=>{let s=colony();expect(abandonColony(s,HOMEWORLD_ID).ok).toBe(false);const p=s.planets[1]!;expect(abandonColony(s,p.id).ok).toBe(false);s=tick(s,nextFleetEvent(s));const gone=abandonColony(selectPlanet(s,p.id),p.id);expect(gone.ok).toBe(true);expect(gone.state.activePlanetId).toBe(HOMEWORLD_ID);});
 it("prestige clears fleets but retains universe and monotonic mission IDs",()=>{let s=sendFleet(ready(),request(ready())).state;s.lifetime.metal=big(1e8);const n=prestige(s);expect(n.fleets).toHaveLength(0);expect(n.planets).toHaveLength(1);expect(n.universe).toEqual(s.universe);expect(n.nextFleetId).toBe(s.nextFleetId);});
 it("does not allow a helper to swallow arrival boundaries",()=>{const s=sendFleet(ready(),request(ready())).state;expect(()=>advanceFleets(s,s.fleets[0]!.duration+1)).toThrow();expect(()=>advanceFleets(s,-1)).toThrow();});
});

describe("space save boundaries",()=>{
 it("round trips outbound, recalled and colonization-return states",()=>{let s=sendFleet(ready(),request(ready())).state;for(const n of [s,tick(s,1),recallFleet(tick(s,1),1).state,tick(s,nextFleetEvent(s))])expect(copy(deserializeState(importSave(exportSave(n,1)).state))).toEqual(copy(n));});
 it.each(["duplicate-coordinate","unknown-origin","duplicate-id","old-next-id","negative-cargo","infinite-time","bad-timer","satellite","empty-ships","deep-target","layout","revision"])("rejects corrupted %s",kind=>{const s=sendFleet(ready(),request(ready())).state;const raw=JSON.parse(exportSave(s,1));const f=raw.state.fleets[0];switch(kind){case "duplicate-coordinate":raw.state.planets.push({...raw.state.planets[0],id:"fake"});break;case "unknown-origin":f.originId="missing";break;case "duplicate-id":raw.state.fleets.push({...f});break;case "old-next-id":raw.state.nextFleetId=1;break;case "negative-cargo":f.cargo.metal="-1";break;case "infinite-time":f.remaining="Infinity";break;case "bad-timer":f.elapsed=1e6;break;case "satellite":f.ships.solar_satellite=1;break;case "empty-ships":f.ships={};break;case "deep-target":f.target.position=16;break;case "layout":raw.state.universe.layout="unknown";break;case "revision":delete raw.revision;}expect(()=>importSave(JSON.stringify(raw))).toThrow();});
 it("r1 save bytes are not silently replaced",()=>{const raw=JSON.parse(exportSave(ready(),1));delete raw.revision;const text=JSON.stringify(raw);const store={getItem:(key:string)=>key===STORAGE_KEY?text:null,setItem:()=>{throw Error("must not write");},removeItem:()=>{throw Error("must not remove");}};expect(()=>loadGame(store,1)).toThrow("修订不兼容");expect(store.getItem(STORAGE_KEY)).toBe(text);});
 it("presenter reports real ships, pre-reservation and locked deep-space entry",()=>{const s=ready();const m=spaceView(s,activePlanet(s).coordinates,request(s));expect(m.rows).toHaveLength(16);expect(m.rows[15]!.canColonize).toBe(false);expect(m.ships.find(x=>x.id==="colony_ship")?.count).toBe(3);expect(m.quote.ok).toBe(true);});
});
