declare const process: { stdout: { write(text: string): void } };
/** Anonymous, un-funded fixtures generated by the real initial-state serializer. */
import { STORAGE_KEY } from "../src/game/content";
import { BACKUP_KEY, exportSave } from "../src/game/save";
import { createInitialState } from "../src/game/state";

function fixture(name: string, seed: number) {
  const state = createInitialState(seed);
  state.arcade.seed = seed;
  state.planets[0].name = name;
  return JSON.parse(exportSave(state, Date.now()));
}

process.stdout.write(JSON.stringify({
  description: "Synthetic initial states only; no player data or progression unlocks.",
  key: STORAGE_KEY,
  backupKey: BACKUP_KEY,
  current: fixture("合成当前母星", 20261001),
  imported: fixture("合成导入母星", 20261002),
  newer: fixture("合成后续母星", 20261003),
}, null, 2));
